### ISSUE TITLE
[Feature Request] configuration per filetype

### ISSUE THREAD

**Issue by doongjohn** [brenoprata10/nvim-highlight-colors#28]
https://github.com/norcalli/nvim-colorizer.lua#customization
```lua
-- Attach to certain Filetypes, add special configuration for `html`
-- Use `background` for everything else.
require 'colorizer'.setup {
  'css';
  'javascript';
  html = {
    mode = 'foreground';
  }
}
```

**Comment by andrewferrier** [comment]
Agreed, this would be great. As an example, `nvim-highlight-colors` throws false positives right now on line numbers in https://github.com/elihunter173/dirbuf.nvim/ buffers, so it would be great to have a way to turn it off for specific filetypes.

Thanks for your hard work on this plugin!

**Comment by catgoose** [comment]
This is the only thing keeping me from switching from my fork of [nvchad/n](https://github.com/norcalli/nvim-colorizer.lua)

**Comment by brenoprata10** [comment]
Hey o/

I do not really plan to support the same structure as colorizer. My goal is to keep the plugin as lightweight and easy to maintain as possible. Otherwise, I might feel unmotivated to keep improving it.

I've just pushed the following PR: https://github.com/brenoprata10/nvim-highlight-colors/pull/87
This PR adds a bunch of options to customize the plugin. Like `enable_hex, enable_rgb`... 
There is a function within vim API which will return the buffer type of the currently opened buffer
`vim.bo.filetype`

If you make use of `vim.bo.filetype`. You can actually turn on/off specific options based on the filetype.

Example of how to disable hex color for buffer of type `text`

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26099427/56060611-de49-4207-906e-62888aab3257)


I understand this is not necessarily what you all wanted. But I hope this will at least open up the customization a little bit 😺

**Comment by rodhash** [comment]
Any idea why this plugins works on CSS + JSX files but not JS?

Specially `named_colors` I can't make it work on JS but in other FT work.
