### ISSUE TITLE
[Feature Request] Virtual text version

### ISSUE THREAD

**Issue by nyngwang** [brenoprata10/nvim-highlight-colors#30]
I would like to show the color preview via virtual text instead of showing it in the first column, is this possible?

**Comment by Rolv-Apneseth** [comment]
This is a feature in [nvim-colorizer](https://github.com/NvChad/nvim-colorizer.lua) and I believe it would work much better visually than the current `first_column` approach, as that one can't display multiple colours on the same line. I do prefer the background option but the issue is when the colour is white, I can't see where the cursor if it's over the colour, so this feature would be very appreciated.

**Comment by brenoprata10** [comment]
Virtual text is now available!
Please give it a try and report any bugs 😄

**Comment by brenoprata10** [comment]
Check README for more information

**Comment by brenoprata10** [comment]
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26099427/f707db49-8302-48ab-ad2d-1da4864667a6)

**Comment by nyngwang** [comment]
@brenoprata10 Thank you! Let's go!!!

**Comment by brenoprata10** [comment]
Which square ascii are you using in your config?
