### ISSUE TITLE
Named colours still don't work with pure CSS.

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [brenoprata10/nvim-highlight-colors#39]
Greetings, great plugin.

I'm switching from `Colorizer` to this plugin because it has more functionality, it's great.

I only noticed a few small problems with CSS.
When using `@define-color` in pure CSS, the named colours still don't work.
Or is this something I have to fix in the configuration? Because I have already enabled the highlighting of named colours in the configuration, and it still doesn't work.

In the screenshot you can see that the named colour `white` has no highlighting, neither does `@window_bg_color`.

![named-colors-issue](https://github.com/brenoprata10/nvim-highlight-colors/assets/47998118/e9142c87-a181-4c33-8576-653278755bbd)

**Comment by genzj** [comment]
Encounter the same problem. I believe the issue lies with the [`M.color_usage_regex = "[:=]+%s*"`](https://github.com/brenoprata10/nvim-highlight-colors/blob/e1c976a31d19c10e77b89e054310b1061acb5158/lua/nvim-highlight-colors/buffer_utils.lua#L5) setting, which mandates that a `:` or `=` must precede the colour name.

I assume that making `:` and `=` optional would make the colour name pattern too broad and result in unintended highlights, so it may not be a suitable solution. But can we use filetype or treesitter to restrict its scope so that `[:=]` can be optional in certain context?

**Comment by brenoprata10** [comment]
This is a behavior that i don't really see how to fix without breaking other parts of the plugin, therefore i don't plan supporting it
