### ISSUE TITLE
whenever I switch the buffer, the highlight colors are gone

### ISSUE THREAD

**Issue by sergiornelas** [brenoprata10/nvim-highlight-colors#73]
If I change the buffer using for example <c-^>, and return back, the highlight colors dissappears:
<img width="195" alt="image" src="https://github.com/brenoprata10/nvim-highlight-colors/assets/42797252/5bfcd0b1-2657-4a03-a8f3-96daae05551e">
<img width="169" alt="image" src="https://github.com/brenoprata10/nvim-highlight-colors/assets/42797252/33b67562-2050-4025-ae9e-8d17ada758b6">

**Comment by brenoprata10** [comment]
Hey o/
Thanks for reporting the issue. I've investigated this bug and I recommend opening an issue in neovim instead.
Here is what is happening:
1. My plugin i receiving the buffer id from the autocmd callback;
2. I fetch the window id for the buffer with `vim.fn.bufwinid`;
3. I call `nvim_win_call` with the window id and then I fetch the start and end line of the current window with `vim.fn.line('w0')` and `vim.fn.line(w$)`;
4. When triggering `<c-^>`, neovim returns 1 for both `vim.fn.line` calls, which obviously will not highlight anything.

This is definetely a neovim bug which is not returning the correct values when calling `vim.fn.line`. I will be closing this issue since there is nothing I can do on my side to fix this.
